### ISSUE TITLE
Change homepage to https

### ISSUE THREAD

**Issue by ryandesign** [newville/ifeffit#5]
The homepage of this GitHub project, as well as URLs embedded in the source code in many places, refer to:

http://cars9.uchicago.edu/ifeffit/

The server does not respond to http. It does respond to https so the URLs should be changed from http to https everywhere they appear.

In addition, the administrators of the server should be contacted to ask them to provide a redirect from http to https so that old links such as these are not broken.

**Comment by newville** [comment]
@ryandesign thanks for the suggestion, but no.  The last commit to this project was 7 years ago. Making any change now would give the mistaken impression that any portion of this code is still developed or maintained.  It is not.  The end of this project and its successor were announced in 2012 and has been in continuous development and support since.
